/**
 * Created by gvrousto on 10/27/15.
 */
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class EvenFibonacci {
    private int firstTerm = 1;
    private int secondTerm = 2;

    public int evenFibonacciSum() {
        int L = firstTerm;
        int H = secondTerm;
        int numSum = 0;
        int temp;
        while (H < 4000000) {
            if (H % 2 == 0) {
                numSum += H;
            }
            temp = L + H;
            L = H;
            H = temp;
        }
        return numSum;
    }
    public static void main(String[] args){
        EvenFibonacci Alexa = new EvenFibonacci();
        System.out.println(Alexa.evenFibonacciSum());
    }
}
